spring:
  datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:mysql://localhost:3306/websocket
    username: websocket
    password: websocket
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    sql.init.mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 107336406920-qj6vo7aku3a7v98uml21ibe9ut9bcdv2.apps.googleusercontent.com
            clientSecret: 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

jwt:
  secret-key: chat.websocket-applicaion-2023.secret_key
  # 30 days 24*60*60*30
  token.expired-time-ms: 2592000000